In [3]:
import sys
import os
import math
sys.path.append("../")
sys.path.append("../../")

In [4]:
from scale_rl.common.wandb_utils import *

In [5]:
MUJ_STEPS = 1000000 # 1M
DMC_STEPS = 1000000 # 1M
MYO_STEPS = 1000000 # 1M
HB_STEPS = 1000000 # 1M

In [6]:
from scale_rl.envs.mujoco import MUJOCO_ALL, MUJOCO_RANDOM_SCORE, MUJOCO_TD3_SCORE
from scale_rl.envs.dmc import DMC_EASY_MEDIUM, DMC_HARD
from scale_rl.envs.humanoid_bench import HB_LOCOMOTION_NOHAND, HB_RANDOM_SCORE, HB_SUCCESS_SCORE
from scale_rl.envs.myosuite import MYOSUITE_TASKS

def replace_hypen_to_underbar(env_name_list):
    for idx in range(len(env_name_list)):
        env_name_list[idx] = env_name_list[idx].replace('_', '-')
    return env_name_list
def replace_hypen_to_underbar_dict(env_name_dict):
    _new_dict = {}
    for k, v in env_name_dict.items():
        _new_dict[k.replace('_', '-')] = v
    return _new_dict

MUJOCO_ALL = replace_hypen_to_underbar(MUJOCO_ALL)
DMC_EASY_MEDIUM = replace_hypen_to_underbar(DMC_EASY_MEDIUM)
DMC_HARD = replace_hypen_to_underbar(DMC_HARD)
HB_LOCOMOTION_NOHAND = replace_hypen_to_underbar(HB_LOCOMOTION_NOHAND)
MYOSUITE_TASKS = replace_hypen_to_underbar(MYOSUITE_TASKS)
HB_LOCOMOTION_NOHAND = replace_hypen_to_underbar(HB_LOCOMOTION_NOHAND)

DMC_ALL = [*DMC_EASY_MEDIUM, *DMC_HARD]

/home/nas4_user/youngdolee/anaconda3/envs/scale_rl/lib/python3.9/site-packages/glfw/__init__.py:916: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)

In [7]:
eval_df = pd.read_csv('../results/hypersimba/hypersimba.csv', index_col=0)
eval_df = eval_df[eval_df["metric"] == "avg_return"]
eval_df = eval_df[eval_df["env_name"].isin(MUJOCO_ALL)]

In [8]:
entity = 'draftrec'
project_name = 'Simba_2412'
run_exp_names_to_analysis_exp_names = {
    'hypersimba_metrics': 'SimbaV2_rr4_mujoco',
}
run_exp_names = list(run_exp_names_to_analysis_exp_names.keys())
metrics = ['avg_return', 'avg_success']

In [9]:
runs = collect_runs(entity=entity, project_name=project_name) 
filtered_runs = filter_runs(runs, exp_names = run_exp_names)
wandb_df = convert_runs_to_dataframe(
    runs = filtered_runs, 
    run_exp_name_to_analysis_exp_name=run_exp_names_to_analysis_exp_names
)
wandb_df = wandb_df[wandb_df.apply(lambda row: 'finished' in str(row['run']), axis=1)]
simbav2_rr4_muj_df = convert_wandb_df_to_eval_df(wandb_df, metrics)

  0%|          | 0/2830 [00:00<?, ?it/s]

  0%|          | 0/285 [00:00<?, ?it/s]

  0%|          | 0/285 [00:00<?, ?it/s]

In [15]:
simbav2_rr4_muj_df['env_name'] = simbav2_rr4_muj_df['env_name'].str.replace('_', '-')
simbav2_rr4_muj_df = simbav2_rr4_muj_df[simbav2_rr4_muj_df['env_name'].isin(MUJOCO_ALL)]
simbav2_rr4_muj_df

,exp_name,env_name,seed,metric,env_step,value
176,SimbaV2_rr4_mujoco,Humanoid-v4,2000,avg_return,0.0,192.081281
177,SimbaV2_rr4_mujoco,Humanoid-v4,2000,avg_return,50000.0,480.805753
178,SimbaV2_rr4_mujoco,Humanoid-v4,2000,avg_return,100000.0,834.928089
179,SimbaV2_rr4_mujoco,Humanoid-v4,2000,avg_return,150000.0,3971.113663
180,SimbaV2_rr4_mujoco,Humanoid-v4,2000,avg_return,200000.0,6388.896293
...,...,...,...,...,...,...
4125,SimbaV2_rr4_mujoco,HalfCheetah-v4,2000,avg_success,800000.0,0.000000
4126,SimbaV2_rr4_mujoco,HalfCheetah-v4,2000,avg_success,850000.0,0.000000
4127,SimbaV2_rr4_mujoco,HalfCheetah-v4,2000,avg_success,900000.0,0.000000
4128,SimbaV2_rr4_mujoco,HalfCheetah-v4,2000,avg_success,950000.0,0.000000
4129,SimbaV2_rr4_mujoco,HalfCheetah-v4,2000,avg_success,1000000.0,0.000000

In [11]:
entity = 'draftrec'
project_name = 'Simba_2501'
run_exp_names_to_analysis_exp_names = {
    'hypersimba_rr1': 'SimbaV2_rr1',
    'hypersimba_rr4': 'SimbaV2_rr4',
    'hypersimba_rr8': 'SimbaV2_rr8',
}
run_exp_names = list(run_exp_names_to_analysis_exp_names.keys())
metrics = ['avg_return', 'avg_success']

In [12]:
runs = collect_runs(entity=entity, project_name=project_name) 
filtered_runs = filter_runs(runs, exp_names = run_exp_names)
wandb_df = convert_runs_to_dataframe(
    runs = filtered_runs, 
    run_exp_name_to_analysis_exp_name=run_exp_names_to_analysis_exp_names
)
wandb_df = wandb_df[wandb_df.apply(lambda row: 'finished' in str(row['run']), axis=1)]
eval_df = convert_wandb_df_to_eval_df(wandb_df, metrics)

  0%|          | 0/2407 [00:00<?, ?it/s]

  0%|          | 0/645 [00:00<?, ?it/s]

  0%|          | 0/644 [00:00<?, ?it/s]

In [13]:
eval_df['env_name'] = eval_df['env_name'].str.replace('_', '-')
eval_df

          exp_name         env_name  seed       metric   env_step        value
0      SimbaV2_rr4      Humanoid-v4  1000   avg_return        0.0   140.503822
1      SimbaV2_rr4      Humanoid-v4  1000   avg_return    50000.0   645.081187
2      SimbaV2_rr4      Humanoid-v4  1000   avg_return   100000.0  3211.023977
3      SimbaV2_rr4      Humanoid-v4  1000   avg_return   150000.0  6833.385995
4      SimbaV2_rr4      Humanoid-v4  1000   avg_return   200000.0  2509.344562
...            ...              ...   ...          ...        ...          ...
15135  SimbaV2_rr8  acrobot-swingup     0  avg_success   600000.0     0.000000
15136  SimbaV2_rr8  acrobot-swingup     0  avg_success   700000.0     0.000000
15137  SimbaV2_rr8  acrobot-swingup     0  avg_success   800000.0     0.000000
15138  SimbaV2_rr8  acrobot-swingup     0  avg_success   900000.0     0.000000
15139  SimbaV2_rr8  acrobot-swingup     0  avg_success  1000000.0     0.000000

[15140 rows x 6 columns]